#ifndef GLOBALES_H
#define GLOBALES_H
#include "virtual_disk.h"

//DEFINIR UNA PLANTILLA GLOBAL PARA VER LOS DISCOS MONTADOS EN EL SISTEMA
extern Discos_Montados *discos_montados[27];

//DEFINIR EL TAMANO DE LOS APUNTADORES DE LOS INODOS
extern int TAM_BLOQUES_INODOS;

#endif //GLOBALES_H